export const allProjects = [
  {
    id: 1,
    title: "Bar \n Stock",
    copy: "Native application for the frugal bar owner. View Distributor’s liquor products. Estimate overall cost of orders, analyze projected profits, and send order through text or email.",
    projectImage: "barStockBG",
    deviceImage: "barStockDevice",
    featured: true,
    type: "Native Application",
    builtWith: ["react native", "javascript", "redux", "ruby"],
    gitHub: "https://github.com/MRKrog/barstock-rn",
  },
  {
    id: 2,
    title: "Movie \n Tracker",
    copy: "A Web application fashioned after Netflix.com. Explore upcoming movies, view ratings, and preview the newest trailers. Ability to create an account and save favorite movies to be viewed at a later date.",
    projectImage: "movieTrackerBG",
    deviceImage: "movieTrackerDevice",
    featured: true,
    type: "Web Application",
    builtWith: ["reactjs", "javascript", "redux", "nodejs"],
    gitHub: "https://github.com/MRKrog/Movie-Tracker",
  },
  {
    id: 3,
    title: "Weather \n Mind",
    copy: "WeatherMind is my take on the Apple IOS weather app. Retrieves real time weather at current location. Includes the ability to search for specific weather forecasts around the world.",
    projectImage: "weatherMindBG",
    deviceImage: "weatherMindDevice",
    featured: true,
    type: "Web Application",
    builtWith: ["reactjs", "javascript", "redux", "nodejs", "darksky api"],
    gitHub: "https://github.com/MRKrog/WeatherMind",
  },
  {
    id: 4,
    title: "Palette \n Picker",
    copy: "Palette Picker is a single page application that gives the user the ability to generate custom color palettes, lock colors, and save palettes to projects for future design inspirations.",
    projectImage: "palettePickerBG",
    deviceImage: "palettePickerDevice",
    featured: false,
    type: "Web Application",
    builtWith: ["reactjs", "javascript", "redux", "nodejs", "material-ui"],
    gitHub: "https://github.com/MRKrog/palette-ui",
    liveLink: "https://paletteui.herokuapp.com/"
  },
  {
    id: 5,
    title: "Trapper \n Keeper",
    copy: "Web Application based on the user functionality of Google Keep. You can add and save notes. Notes can also be edited, list items marked as completed, and the background color of the note can be changed.",
    projectImage: "trapperKeeperBG",
    deviceImage: "trapperKeeperDevice",
    featured: false,
    type: "Web Application",
    builtWith: ["reactjs", "javascript", "redux", "nodejs"],
    gitHub: "https://github.com/MRKrog/TrapperKeeper",
  },
  {
    id: 6,
    title: "Fish-On \n Tempress",
    copy: "Custom creation and design of customer Ecommerce website and user experience. Tempress focuses on fishing and the outdoor industry, created customer experience focusing on modern design and usability.",
    projectImage: "tempressBG",
    deviceImage: "tempressDevice",
    featured: false,
    type: "Ecommerce Website",
    builtWith: ["wordpress", "jquery", "php", "wocommerce"],
    gitHub: "https://tempress.com/",
    liveLink: "https://tempress.com/",
  },
  {
    id: 6,
    title: "Seize \n The Seven",
    copy: "Custom Campaign Landing Page for Winter Park Resort's 2017-18 winter season. The focus of this landing page was to introduce 7 Ambassadors for each of the unique 7 territories of Winter Park Resort.",
    projectImage: "seizeTheSevenBG",
    deviceImage: "seizeTheSevenDevice",
    featured: false,
    type: "Custom Campaign",
    builtWith: ["javascript", "jquery", "html", "css"],
    gitHub: "https://github.com/MRKrog/SeizeTheSeven",
    liveLink: "https://mrkrog.github.io/SeizeTheSeven/Home.html",
  }
]
