export const allProjects = [
  {
    id: 1,
    title: "Bar \n Stock",
    copy: "BarStock is a native application with the ability to place orders from their distributors, analyze profit margins, and automate text message/email ordering.",
    projectImage: "barStockBG",
    deviceImage: "barStockDevice",
    featured: true,
    type: "Native Application",
    builtWith: ["react native", "javascript", "redux", "ruby"],
    gitHub: "https://github.com/MRKrog/barstock-rn",
  },
  {
    id: 2,
    title: "Movie \n Tracker",
    copy: "Web application that allows the user to view the best movie of every genre and have the ability to save their favorite movies to view the information later.",
    projectImage: "movieTrackerBG",
    deviceImage: "movieTrackerDevice",
    featured: true,
    type: "Web Application",
    builtWith: ["reactjs", "javascript", "redux", "nodejs"],
    gitHub: "https://github.com/MRKrog/Movie-Tracker",
  },
  {
    id: 3,
    title: "Weather \n Mind",
    copy: "Web Application my take on the Apple IOS weather app. Gets real time weather of your location with the ability to search locations.",
    projectImage: "weatherMindBG",
    deviceImage: "weatherMindDevice",
    featured: true,
    type: "Web Application",
    builtWith: ["reactjs", "javascript", "redux", "nodejs", "darksky api"],
    gitHub: "https://github.com/MRKrog/WeatherMind",
  },
  {
    id: 4,
    title: "Weather \n Mind 2",
    copy: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna.",
    projectImage: "projectImage",
    deviceImage: "movieTrackerDevice",
    featured: false,
    type: "Web Application",
    builtWith: ["reactjs", "javascript", "redux", "ruby"],
    gitHub: "",
  }
]
